[[queries]]
name = "test1"

[[queries.revisions]]
name = "1.0.0"
query = '''
SELECT id,name FROM test where name like '%foo%';
'''
pre_script = '''
CREATE TABLE test (id BIGSERIAL PRIMARY KEY, name TEXT);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
INSERT INTO test (name) SELECT gen_random_uuid() from generate_series(1,100);
'''
post_script = '''
DROP TABLE test;
'''

[[queries.revisions]]
name = "2.0.0"
query = "SELECT id,name FROM test where name like '%foo%';"
pre_script = '''
CREATE TABLE test (id BIGSERIAL PRIMARY KEY, name TEXT);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
INSERT INTO test (name) SELECT gen_random_uuid() from generate_series(1,100);
CREATE INDEX test_name_idx ON test (name);
'''
post_script = "DROP TABLE test;"

[[queries]]
name = "test2"

[[queries.revisions]]
name = "1.0.0"
query = '''
SELECT id,name FROM test where name like '%foo%';
'''
pre_script = '''
CREATE TABLE test (id BIGSERIAL PRIMARY KEY, name TEXT);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
INSERT INTO test (name) SELECT gen_random_uuid() from generate_series(1,100);
'''
post_script = '''
DROP TABLE test;
'''

[[queries.revisions]]
name = "2.0.0"
query = "SELECT id,name FROM test where name like '%foo%';"
pre_script = '''
CREATE TABLE test (id BIGSERIAL PRIMARY KEY, name TEXT);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
INSERT INTO test (name) SELECT gen_random_uuid() from generate_series(1,100);
CREATE INDEX test_name_idx ON test (name);
'''
post_script = "DROP TABLE test;"
