name: QBench Release
permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - v*.*.*


jobs:
  check-build:
    name: Check build
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
        platform: [ubuntu-latest]
        include:
          - target: x86_64-apple-darwin
            platform: macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      # - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
      #   name: Cargo Cache
      #   with:
      #     command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Cargo build
        with:
          command: cargo build
          use-cross: true
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: qbench-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/qbench
            target/${{ matrix.target }}/release/qbench.exe
          if-no-files-found: error

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
      #   name: Cargo cache
      #   with:
      #     command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install Rustup
        with:
          command: install-rustup
          toolchain: stable
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Run tests
        with:
          command: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
      #   name: Cargo cache
      #   with:
      #     command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install Rustup
        with:
            command: install-rustup
            toolchain: stable
            components: clippy
            default: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Clippy
        with:
          command: cargo clippy