name: QBench Release
permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Test linux
        run: cargo test --all --release

      - name: Build for linux
        run: cargo build --all --release && strip target/release/qbench

      - name: Archive linux artifact
        run: tar -czvf qbench-linux_amd64.tar.gz target/release/qbench

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qbench-linux_amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Test windows
        run: cargo test --all --release

      - name: Build for windows
        run: cargo build --all --release

      - name: Archive windows artifact
        shell: pwsh
        run: Compress-Archive -Path target/release/qbench.exe -DestinationPath qbench-windows_amd64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qbench-windows_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Test macos
        run: cargo test --all --release

      - name: Build for macos
        run: cargo build --all --release && strip target/release/qbench

      - name: Archive macos artifact
        run: zip qbench-macos_amd64.zip target/release/qbench

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/qbench-macos_amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}